// <auto-generated />
using System;
using Feed.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Feed.Core.Infrastructure.Migrations
{
    [DbContext(typeof(FeedDb))]
    [Migration("20260928082802_RecoveryDiagnostics")]
    partial class RecoveryDiagnostics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Feed.Core.Domain.Author", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFriend")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformAuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "IsFriend");

                    b.HasIndex("Platform", "PlatformAuthorId")
                        .IsUnique();

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Feed.Core.Domain.AuthorKey", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<long>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("AuthorId");

                    b.ToTable("AuthorKeys");
                });

            modelBuilder.Entity("Feed.Core.Domain.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoriesAtVote")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Curated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<long>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonAtVote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScoreAtVote")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ViewKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Feed.Core.Domain.Kv", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Kv");
                });

            modelBuilder.Entity("Feed.Core.Domain.Like", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .IsUnique()
                        .HasFilter("State = 'pending'");

                    b.HasIndex("PostId", "State");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Feed.Core.Domain.Media", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PrunedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("Kind", "IsCurrent", "AttemptedAt", "CreatedAt")
                        .HasFilter("Path IS NULL AND PrunedAt IS NULL");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("Feed.Core.Domain.PlatformState", b =>
                {
                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastOkRunAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunFinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsRelogin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Platform");

                    b.ToTable("PlatformStates");
                });

            modelBuilder.Entity("Feed.Core.Domain.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoriesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HiddenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HiddenBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("HiddenReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IngestReadyAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEvent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSponsored")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuggested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("JudgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestRawRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("LikeRef")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LlmAttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmError")
                        .HasColumnType("TEXT");

                    b.Property<int>("LlmFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlmReason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LlmScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaManifestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedAuthorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedAuthorUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Permalink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformPostId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrefsVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedAuthor")
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SummarizedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SummaryAttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SummaryContentRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryEndpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryError")
                        .HasColumnType("TEXT");

                    b.Property<int>("SummaryFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryInputHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerdictContentRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerdictEndpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerdictInputHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerdictModel")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisibilityRevision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostedAt");

                    b.HasIndex("Hidden", "PostedAt");

                    b.HasIndex("Platform", "PlatformPostId")
                        .IsUnique();

                    b.HasIndex("Platform", "LlmAttemptedAt", "CapturedAt")
                        .HasDatabaseName("IX_Posts_JudgeQueue")
                        .HasFilter("IngestReadyAt IS NOT NULL AND (Hidden = 0 OR HiddenBy = 'llm') AND (CategoriesJson IS NULL OR VerdictContentRevision IS NULL OR VerdictContentRevision <> ContentRevision)");

                    b.HasIndex("Platform", "SummaryAttemptedAt", "CapturedAt")
                        .HasDatabaseName("IX_Posts_SummaryQueue")
                        .HasFilter("IngestReadyAt IS NOT NULL AND Hidden = 0 AND (Summary IS NULL OR SummaryContentRevision IS NULL OR SummaryContentRevision <> ContentRevision)");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Feed.Core.Domain.RawSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BlockedParserVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Parsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ParsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("Platform", "CapturedAt");

                    b.HasIndex("Platform", "AttemptedAt", "CapturedAt")
                        .HasFilter("Parsed = 0 AND Deleted = 0");

                    b.ToTable("RawSnapshots");
                });

            modelBuilder.Entity("Feed.Core.Domain.Run", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostsFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostsNew")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessPid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProcessStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawDir")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinishedAt");

                    b.HasIndex("RequestId");

                    b.HasIndex("Platform", "Status");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("Feed.Core.Domain.RunRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChildPid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ChildStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetryIncomplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind")
                        .IsUnique()
                        .HasFilter("Status IN ('pending','claimed') AND Kind = 'process'");

                    b.HasIndex("Kind", "Platform")
                        .IsUnique()
                        .HasFilter("Status IN ('pending','claimed') AND Kind IN ('collect','like')");

                    b.HasIndex("Status", "RequestedAt");

                    b.ToTable("RunRequests", t =>
                        {
                            t.HasCheckConstraint("CK_RequestScope", "(Kind = 'process' AND Platform IS NULL) OR (Kind IN ('collect','like') AND Platform IN ('facebook','instagram'))");
                        });
                });

            modelBuilder.Entity("Feed.Core.Domain.SweepTarget", b =>
                {
                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<string>("CycleId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RetryAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("VisitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Platform", "CycleId", "AuthorId");

                    b.ToTable("SweepTargets");
                });

            modelBuilder.Entity("Feed.Core.Domain.TimelineVisit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaptureStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NewestPostedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OldestPostedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostsFound")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Screenshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StopReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "Url", "Id");

                    b.ToTable("TimelineVisits");
                });

            modelBuilder.Entity("Feed.Core.Domain.AuthorKey", b =>
                {
                    b.HasOne("Feed.Core.Domain.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feed.Core.Domain.Media", b =>
                {
                    b.HasOne("Feed.Core.Domain.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feed.Core.Domain.Post", b =>
                {
                    b.HasOne("Feed.Core.Domain.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
