<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AllowUnsafeBlocks>true</AllowUnsafeBlocks></PropertyGroup><ItemGroup><PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" /><PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" /><PackageReference Include="Microsoft.Extensions.Logging" /></ItemGroup></Project>
